// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdS-gft78w37qmK6qiSyjiGsqAAxKSYow',
    appId: '1:516379067553:web:7a7394d7ca28990bb89ce0',
    messagingSenderId: '516379067553',
    projectId: 'wahyu-dwi-mdtest-18bd3',
    authDomain: 'wahyu-dwi-mdtest-18bd3.firebaseapp.com',
    storageBucket: 'wahyu-dwi-mdtest-18bd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHIDPmeEZkjIhFvDdO72NqocQ2q4C-Kp4',
    appId: '1:516379067553:android:679a643a1f48e25bb89ce0',
    messagingSenderId: '516379067553',
    projectId: 'wahyu-dwi-mdtest-18bd3',
    storageBucket: 'wahyu-dwi-mdtest-18bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9mTPUpPwisHmRJsPqBdhOFQRFMHJuqo',
    appId: '1:516379067553:ios:f68ad8469b6d7331b89ce0',
    messagingSenderId: '516379067553',
    projectId: 'wahyu-dwi-mdtest-18bd3',
    storageBucket: 'wahyu-dwi-mdtest-18bd3.firebasestorage.app',
    iosBundleId: 'com.example.wahyuDwiMdtest',
  );
}
