// Mocks generated by Mockito 5.4.6 from annotations
// in wahyu_dwi_mdtest/test/presentation/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wahyu_dwi_mdtest/domain/entities/user_entity.dart' as _i4;
import 'package:wahyu_dwi_mdtest/domain/usecase/home/get_users_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersUseCase extends _i1.Mock implements _i2.GetUsersUseCase {
  @override
  _i3.Stream<List<_i4.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Stream<List<_i4.UserEntity>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.UserEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.UserEntity>>);
}
