// Mocks generated by Mockito 5.4.6 from annotations
// in wahyu_dwi_mdtest/test/data/repositories/home/home_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wahyu_dwi_mdtest/data/models/auth/user_model.dart' as _i4;
import 'package:wahyu_dwi_mdtest/data/sources/home/home_remote_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteSource extends _i1.Mock implements _i2.HomeRemoteSource {
  @override
  _i3.Stream<List<_i4.UserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i3.Stream<List<_i4.UserModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.UserModel>>.empty(),
          )
          as _i3.Stream<List<_i4.UserModel>>);
}
